/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      label: 'Getting Started',
      id: 'getting-started',
    },
    {
      type: 'doc',
      label: 'Building New Switches',
      id: 'building-new-switches',
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        {
          type: 'doc',
          label: 'Setups',
          id: 'Deployments/Shared/setups'
        },
        {
          type: 'category',
          label: 'AWS',
          items: [
            {
              type: 'doc',
              label: 'Deploying to Amazon Web Services (AWS)',
              id: 'Deployments/AWS/deploying-to-aws'
            },
            {
              type: 'doc',
              label: 'Manually Setup',
              id: 'Deployments/AWS/manual-setup-for-aws'
            }
          ]
        },
        {
          type: 'doc',
          label: 'Rate Limiting',
          id: 'Deployments/Shared/rate-limiting'
        }
      ],
    },


    // {
    //   type: 'doc',
    //   label: 'Tutorial',
    //   id: 'intro',
    // },
  ],
};

module.exports = sidebars;
