name: Main
on:
  push:
    branches:
      - main
    tags:
      - '!refs/tags/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Deploy
        run: |
          echo "Test"
